### ISSUE TITLE
Ability to pass environment vars to docker-compose up

### ISSUE THREAD

**Issue by pzbitskiy** [avast/docker-compose-gradle-plugin#26]
*Use case:* using the same YML file for integration test environment and for manual QA verification. YML file contains environment variables and there no way to pass them to composeUp task so that *docker-compose up/build* can interpolate.

I'm primary interested in setting HOST_IP var that is discovered by plugin as ServiceInfo.host but ability to pass any env to *docker-compose up/build* is quite generic.

**Comment by augi** [comment]
Can you please add some examples? I haven't got the point :( Thanks!

**Comment by pzbitskiy** [comment]
Suppose we have the following YML file that is used in autotest and manual tests:
```
version: '2'

services:
    backend:
        image: 192.168.1.100:5000/backend:latest
        restart: always
        ports:
            - 8000:8000
    ui:
        image: 192.168.1.100:5000/ui:latest
        restart: always
        ports:
            - 80:80
        environment:
            BACKEND_ADDRESS: "http://${BACKEND_HOST}:8000"
```
Integration tests are run with *gradle integTest* that depends on *composeUp*. I need to set *BACKEND_HOST* to backend service address - that is either $DOCKER_HOST or localhost depending on setup. Now no way to pass such into to docker-compose using the plugin although all info is available in the plugin.
